# Generated by Django 4.0.1 on 2022-02-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='typee',
        ),
    ]
