# Generated by Django 4.0.1 on 2022-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_remove_apply_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
