# Generated by Django 4.0.1 on 2022-02-20 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_apply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
