# Generated by Django 4.0.2 on 2022-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_apply_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='profile_pic_url',
            field=models.CharField(default=3, max_length=400),
            preserve_default=False,
        ),
    ]
