# Generated by Django 4.0.2 on 2022-03-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_alter_apply_main_image_alter_apply_phone_number_and_more'),
    ]

    operations = [
    ]
