# Generated by Django 4.0.1 on 2022-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0002_remove_applybookmark__id_applybookmark_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybookmark',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
