# Generated by Django 4.0.1 on 2022-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0003_alter_applybookmark_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybookmark',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
    ]
