# Generated by Django 4.0.1 on 2022-02-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0004_alter_applybookmark_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybookmark',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='number_of_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='number_of_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
