# Generated by Django 4.0.1 on 2022-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0005_alter_applybookmark_address_alter_applybookmark_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applybookmark',
            name='first_name',
        ),
    ]
