# Generated by Django 4.0.1 on 2022-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0006_remove_applybookmark_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybookmark',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applybookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
