# Generated by Django 4.0.2 on 2022-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applybookmark', '0008_remove_applybookmark_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybookmark',
            name='user_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item_id',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
