# Generated by Django 4.0.2 on 2022-03-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_city_user_name_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_userid', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone_number', models.CharField(max_length=50)),
                ('receiver_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_userid', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_phone_number', models.CharField(max_length=50)),
                ('sender_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chat.receiver'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat.sender'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
