# Generated by Django 4.0.2 on 2022-03-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('receiver__receiver_userid',)},
        ),
    ]
