# Generated by Django 4.0.2 on 2022-03-04 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 13, 9, 7, 950434, tzinfo=utc)),
        ),
    ]
